TransparencyComponent#14590
baltimorecounty/dotgov-prototype-2.0 pull request #13
Opened 2019-09-13 17:08 UTC by sgrg1

worked on Transparency Component

2019-09-13 17:27 UTC, martypowell commented
@sgrg1 you are going to checkout the class `dg_item-grid` which usage can be found in the "most popular services" section of the prototype. It is possible that we may need to make a similar class to `dg_item-grid` if it doesn't work for these buttons.  Please let me know if you have any questions.

2019-09-13 17:28 UTC, martypowell requested changes
See other comments Integrate dg_item-grid, or alternative if needed (let me know and i can help).

2019-09-17 15:09 UTC, martypowell commented
> @sgrg1 you are going to checkout the class `dg_item-grid` which usage can be found in the "most popular services" section of the prototype. It is possible that we may need to make a similar class to `dg_item-grid` if it doesn't work for these buttons. Please let me know if you have any questions.

This was wrong, but you guys got us on the right track.

2019-09-17 15:57 UTC, martypowell submitted a review, later dismissed
looks good to me.

2019-09-17 15:57 UTC, martypowell commented on src/components/TransparencyGroup.js
> +			<div className="row">
@sgrg1 per our chat, this can be updated like news room.

2019-09-17 15:57 UTC, martypowell commented on src/components/sections/TransparencySection.js
> +			<div className="row">
@sgrg1 wherever this row ends up being you can add a class of `text-center` to align the icon buttons as you wish. I'm not sure where that will be quite yet, but I think you get the point.

2019-09-17 16:03 UTC, martypowell commented
@danfox01 @sdurphy this is ready for a look

https://baltimorecounty.github.io/dotgov-prototype-2.0/#/

2019-09-17 16:07 UTC, danfox01 commented
Looks good. Approved.

2019-09-17 16:12 UTC, merged